### ISSUE TITLE
部分事件的subject player 缺失

### ISSUE THREAD

**Issue by novsamuelquan** [appcell/OverwatchDataAnalysis#13]
部分事件的subject player 缺失

**Comment by appcell** [comment]
@KomorebiL 

这个问题的原因是这样：在识别出killfeed里的subject chara以后，会和当前帧的所有玩家的英雄比对，找出player的名字。但是如果当前帧有某个玩家没识别出来（比如角色死亡以后就无法识别），就无法比对，这时subject player就只能留空。这种情况常常发生在object player上，但有时也会发生在subject player上。

解决方法：倒序搜索前几帧，直到某个frame里有这样一个player：

player.chara == killfeed.player1.chara and player.team == killfeed.player1.team

就把这个player赋给当前的killfeed里的player：

kilfeed.player1.player = player.name

这段必须要在所有frame识别以后完成，所以放在i/o里面

**Comment by KomorebiL** [comment]
已解决
