### ISSUE TITLE
是否可以在自动识别视频中比赛开始时间之前支持手动输入视频的开始时间的功能

### ISSUE THREAD

**Issue by novsamuelquan** [appcell/OverwatchDataAnalysis#15]

**Comment by novsamuelquan** [comment]
是否可以支持通过excel导入队伍和队员名单

**Comment by appcell** [comment]
开始时间那里，gui最近我们可能比较忙没时间更新，你测试时手动改一下/ora/gui.py的33行：

`game.analyze(0, 0)`

第一个0是开始时间，改成你想要的秒数就ok。

正式版不打算加入这个功能，因为英雄识别的基础是最右边的英雄没有大招。如果用户选择开始时间时选了最右边英雄有大招的时间点，就无法正确识别。
