### ISSUE TITLE
不能正确识别REPLAY

### ISSUE THREAD

**Issue by Cornlin** [appcell/OverwatchDataAnalysis#17]
视频：SHD VS BU GAME1
时间点：00:04:48.5 进入REPLAY，此时错误地识别为大招全部准备好。
[SHD VS BU Game1 .xlsx](https://github.com/appcell/OverwatchDataAnalysis/files/1646555/SHD.VS.BU.Game1.xlsx)

**Comment by appcell** [comment]
fix了 老铁有空重测一下
