### ISSUE TITLE
部分object player和object hero的格式变化

### ISSUE THREAD

**Issue by novsamuelquan** [appcell/OverwatchDataAnalysis#21]
2018.1.29 部分object player和object hero本来没有任何内容，格式却变化（表格底色变化），数量很多

视频：SHD VS GLA, 除了Game1，Round1之外的所有比赛 (不代表其他视频无此错误)
第一个测试视频无此错误，其余测试视频均出现错误。

系统：Win 10

**Comment by appcell** [comment]
是excel的问题

**Comment by appcell** [comment]
excel有缓存 有时会用上一个打开的文件的背景色
