### ISSUE TITLE
Player.is_dead waggles between 0 and 1

### ISSUE THREAD

**Issue by Rigel7** [appcell/OverwatchDataAnalysis#47]
Video: OWLS1_W1_D1_M2_SHD_VS_GLA_G3_R2.MP4
Examples:
![image](https://user-images.githubusercontent.com/9484410/36984539-137bc986-20d0-11e8-8307-2cf0b53fd66c.png)
![image](https://user-images.githubusercontent.com/9484410/36984637-51ee3df2-20d0-11e8-87a3-68d7ebd65f47.png)

**Comment by appcell** [comment]
fixed.
